// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: queue-service.proto

package rpc

import (
	queue "github.com/harryrose/godm/queue-service/queue"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearHistoryInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// queue is the identifier of the queue whose history should be cleared
	Queue *queue.Identifier `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
}

func (x *ClearHistoryInput) Reset() {
	*x = ClearHistoryInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearHistoryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryInput) ProtoMessage() {}

func (x *ClearHistoryInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryInput.ProtoReflect.Descriptor instead.
func (*ClearHistoryInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClearHistoryInput) GetQueue() *queue.Identifier {
	if x != nil {
		return x.Queue
	}
	return nil
}

type ClearHistoryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearHistoryResult) Reset() {
	*x = ClearHistoryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearHistoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryResult) ProtoMessage() {}

func (x *ClearHistoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryResult.ProtoReflect.Descriptor instead.
func (*ClearHistoryResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{1}
}

type GetFinishedItemsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// queue is the identifier of the queue whose items should be returned
	Queue *queue.Identifier `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// pagination specifies parameters required for paginating results
	Pagination *PaginationParameters `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *GetFinishedItemsInput) Reset() {
	*x = GetFinishedItemsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFinishedItemsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinishedItemsInput) ProtoMessage() {}

func (x *GetFinishedItemsInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinishedItemsInput.ProtoReflect.Descriptor instead.
func (*GetFinishedItemsInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFinishedItemsInput) GetQueue() *queue.Identifier {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *GetFinishedItemsInput) GetPagination() *PaginationParameters {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetFinishedItemsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pagination specifies the parameters that should be used in the next call to GetQueueItems
	Pagination *PaginationParameters `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// items is the download-ordered list of items in the queue. the first item is the first to be downloaded.
	Items []*IdentifiedQueueItemWithState `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetFinishedItemsResult) Reset() {
	*x = GetFinishedItemsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFinishedItemsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinishedItemsResult) ProtoMessage() {}

func (x *GetFinishedItemsResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinishedItemsResult.ProtoReflect.Descriptor instead.
func (*GetFinishedItemsResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFinishedItemsResult) GetPagination() *PaginationParameters {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetFinishedItemsResult) GetItems() []*IdentifiedQueueItemWithState {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClaimNextItemInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queue *queue.Identifier `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
}

func (x *ClaimNextItemInput) Reset() {
	*x = ClaimNextItemInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimNextItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimNextItemInput) ProtoMessage() {}

func (x *ClaimNextItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimNextItemInput.ProtoReflect.Descriptor instead.
func (*ClaimNextItemInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimNextItemInput) GetQueue() *queue.Identifier {
	if x != nil {
		return x.Queue
	}
	return nil
}

type ClaimNextItemResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *queue.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item *queue.Item       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *ClaimNextItemResult) Reset() {
	*x = ClaimNextItemResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimNextItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimNextItemResult) ProtoMessage() {}

func (x *ClaimNextItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimNextItemResult.ProtoReflect.Descriptor instead.
func (*ClaimNextItemResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimNextItemResult) GetId() *queue.Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ClaimNextItemResult) GetItem() *queue.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// SetItemStateInput is the parameters passed into SetItemState
type SetItemStateInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// item is the identifier of item whose state is to be updated
	Item *queue.Identifier `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// state is the new value of the state. Zero values and unspecified values
	// are ignored.
	State *queue.ItemState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SetItemStateInput) Reset() {
	*x = SetItemStateInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemStateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemStateInput) ProtoMessage() {}

func (x *SetItemStateInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemStateInput.ProtoReflect.Descriptor instead.
func (*SetItemStateInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetItemStateInput) GetItem() *queue.Identifier {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *SetItemStateInput) GetState() *queue.ItemState {
	if x != nil {
		return x.State
	}
	return nil
}

// SetItemStateResult is the result of the SetItemState call.
type SetItemStateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pagination specifies the parameters that should be used in the next call to GetQueueItems
	Pagination *PaginationParameters `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// items is the download-ordered list of items in the queue. the first item is the first to be downloaded.
	Items []*IdentifiedQueueItemWithState `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SetItemStateResult) Reset() {
	*x = SetItemStateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetItemStateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemStateResult) ProtoMessage() {}

func (x *SetItemStateResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemStateResult.ProtoReflect.Descriptor instead.
func (*SetItemStateResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetItemStateResult) GetPagination() *PaginationParameters {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SetItemStateResult) GetItems() []*IdentifiedQueueItemWithState {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetQueueItemsInput is the parameters passed into GetQueueItems
type GetQueueItemsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// queue is the identifier of the queue whose items should be returned
	Queue *queue.Identifier `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// pagination specifies parameters required for paginating results
	Pagination *PaginationParameters `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *GetQueueItemsInput) Reset() {
	*x = GetQueueItemsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueueItemsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueItemsInput) ProtoMessage() {}

func (x *GetQueueItemsInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueItemsInput.ProtoReflect.Descriptor instead.
func (*GetQueueItemsInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetQueueItemsInput) GetQueue() *queue.Identifier {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *GetQueueItemsInput) GetPagination() *PaginationParameters {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetQueueItemsResult is the response from GetQueueItems
type GetQueueItemsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pagination specifies the parameters that should be used in the next call to GetQueueItems
	Pagination *PaginationParameters `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// items is the download-ordered list of items in the queue. the first item is the first to be downloaded.
	Items []*IdentifiedQueueItemWithState `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetQueueItemsResult) Reset() {
	*x = GetQueueItemsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueueItemsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueItemsResult) ProtoMessage() {}

func (x *GetQueueItemsResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueItemsResult.ProtoReflect.Descriptor instead.
func (*GetQueueItemsResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetQueueItemsResult) GetPagination() *PaginationParameters {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetQueueItemsResult) GetItems() []*IdentifiedQueueItemWithState {
	if x != nil {
		return x.Items
	}
	return nil
}

// CancelItemInput is the input to CancelItem
type CancelItemInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// item is the identifier of the item to be cancelled
	Item *queue.Identifier `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CancelItemInput) Reset() {
	*x = CancelItemInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelItemInput) ProtoMessage() {}

func (x *CancelItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelItemInput.ProtoReflect.Descriptor instead.
func (*CancelItemInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{10}
}

func (x *CancelItemInput) GetItem() *queue.Identifier {
	if x != nil {
		return x.Item
	}
	return nil
}

// CancelItemResult is the response from CancelItem
type CancelItemResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelItemResult) Reset() {
	*x = CancelItemResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelItemResult) ProtoMessage() {}

func (x *CancelItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelItemResult.ProtoReflect.Descriptor instead.
func (*CancelItemResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{11}
}

// IdentifiedQueueItemWithState is a pair of an IdentifiedQueueItem and the ItemState describing the current
// progress being made on that item
type IdentifiedQueueItemWithState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the identifier of the item whose state is being reported
	Id *queue.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// item is the item whose state is being reported
	Item *queue.Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	// state is the current download progress of the item
	State *queue.ItemState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// updated is the last time the state was updated
	Updated *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *IdentifiedQueueItemWithState) Reset() {
	*x = IdentifiedQueueItemWithState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifiedQueueItemWithState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifiedQueueItemWithState) ProtoMessage() {}

func (x *IdentifiedQueueItemWithState) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifiedQueueItemWithState.ProtoReflect.Descriptor instead.
func (*IdentifiedQueueItemWithState) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{12}
}

func (x *IdentifiedQueueItemWithState) GetId() *queue.Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IdentifiedQueueItemWithState) GetItem() *queue.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *IdentifiedQueueItemWithState) GetState() *queue.ItemState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *IdentifiedQueueItemWithState) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

// EnqueueItemInput is the input to EnqueueItem
type EnqueueItemInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queue *queue.Identifier `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// item defines the item to be added to the download queue
	Item *queue.Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *EnqueueItemInput) Reset() {
	*x = EnqueueItemInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueueItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueItemInput) ProtoMessage() {}

func (x *EnqueueItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueItemInput.ProtoReflect.Descriptor instead.
func (*EnqueueItemInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{13}
}

func (x *EnqueueItemInput) GetQueue() *queue.Identifier {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *EnqueueItemInput) GetItem() *queue.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// EnqueueItemResult is the response from EnqueueItem
type EnqueueItemResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the identifier for the enqueued item
	Id *queue.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EnqueueItemResult) Reset() {
	*x = EnqueueItemResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueueItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueItemResult) ProtoMessage() {}

func (x *EnqueueItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueItemResult.ProtoReflect.Descriptor instead.
func (*EnqueueItemResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{14}
}

func (x *EnqueueItemResult) GetId() *queue.Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

// CreateQueueInput is the input to CreateQueue
type CreateQueueInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the human-readable name to give to the queue.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateQueueInput) Reset() {
	*x = CreateQueueInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQueueInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueInput) ProtoMessage() {}

func (x *CreateQueueInput) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueInput.ProtoReflect.Descriptor instead.
func (*CreateQueueInput) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateQueueInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateQueueResult is the response from CreateQueue
type CreateQueueResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the identifier for the newly created queue
	Id *queue.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateQueueResult) Reset() {
	*x = CreateQueueResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQueueResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResult) ProtoMessage() {}

func (x *CreateQueueResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResult.ProtoReflect.Descriptor instead.
func (*CreateQueueResult) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateQueueResult) GetId() *queue.Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

// PaginationParameters defines how result lists should be truncated
// such that a client can implement pagination.
type PaginationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// limit is the maximum number of items to return
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// next is the id of the first result that should be returned
	Next *queue.Identifier `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *PaginationParameters) Reset() {
	*x = PaginationParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationParameters) ProtoMessage() {}

func (x *PaginationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_queue_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationParameters.ProtoReflect.Descriptor instead.
func (*PaginationParameters) Descriptor() ([]byte, []int) {
	return file_queue_service_proto_rawDescGZIP(), []int{17}
}

func (x *PaginationParameters) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationParameters) GetNext() *queue.Identifier {
	if x != nil {
		return x.Next
	}
	return nil
}

var File_queue_service_proto protoreflect.FileDescriptor

var file_queue_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63,
	0x1a, 0x0b, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c,
	0x0a, 0x11, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x27, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76,
	0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x57, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x3d, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x22, 0x59, 0x0a, 0x13, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x62, 0x0a, 0x11, 0x53,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x25, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x94, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73,
	0x76, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x7e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x27, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x57, 0x69,
	0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x38,
	0x0a, 0x0f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xc0, 0x01, 0x0a,
	0x1c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22,
	0x5c, 0x0a, 0x10, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x36, 0x0a,
	0x11, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x32, 0xfc, 0x04, 0x0a, 0x0c, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x1b, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1c, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f,
	0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0b, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63,
	0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x1c, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x45, 0x6e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x45, 0x0a, 0x0a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x2e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1b, 0x2e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1d, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f,
	0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1e, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73,
	0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x20, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x21, 0x2e, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x4b, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1c, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1d, 0x2e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4e, 0x0a, 0x0d,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x2e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4e,
	0x65, 0x78, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1e, 0x2e, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4e, 0x65,
	0x78, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4b, 0x0a, 0x0c,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1d, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_queue_service_proto_rawDescOnce sync.Once
	file_queue_service_proto_rawDescData = file_queue_service_proto_rawDesc
)

func file_queue_service_proto_rawDescGZIP() []byte {
	file_queue_service_proto_rawDescOnce.Do(func() {
		file_queue_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_queue_service_proto_rawDescData)
	})
	return file_queue_service_proto_rawDescData
}

var file_queue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_queue_service_proto_goTypes = []interface{}{
	(*ClearHistoryInput)(nil),            // 0: queue_svc.ClearHistoryInput
	(*ClearHistoryResult)(nil),           // 1: queue_svc.ClearHistoryResult
	(*GetFinishedItemsInput)(nil),        // 2: queue_svc.GetFinishedItemsInput
	(*GetFinishedItemsResult)(nil),       // 3: queue_svc.GetFinishedItemsResult
	(*ClaimNextItemInput)(nil),           // 4: queue_svc.ClaimNextItemInput
	(*ClaimNextItemResult)(nil),          // 5: queue_svc.ClaimNextItemResult
	(*SetItemStateInput)(nil),            // 6: queue_svc.SetItemStateInput
	(*SetItemStateResult)(nil),           // 7: queue_svc.SetItemStateResult
	(*GetQueueItemsInput)(nil),           // 8: queue_svc.GetQueueItemsInput
	(*GetQueueItemsResult)(nil),          // 9: queue_svc.GetQueueItemsResult
	(*CancelItemInput)(nil),              // 10: queue_svc.CancelItemInput
	(*CancelItemResult)(nil),             // 11: queue_svc.CancelItemResult
	(*IdentifiedQueueItemWithState)(nil), // 12: queue_svc.IdentifiedQueueItemWithState
	(*EnqueueItemInput)(nil),             // 13: queue_svc.EnqueueItemInput
	(*EnqueueItemResult)(nil),            // 14: queue_svc.EnqueueItemResult
	(*CreateQueueInput)(nil),             // 15: queue_svc.CreateQueueInput
	(*CreateQueueResult)(nil),            // 16: queue_svc.CreateQueueResult
	(*PaginationParameters)(nil),         // 17: queue_svc.PaginationParameters
	(*queue.Identifier)(nil),             // 18: queue.Identifier
	(*queue.Item)(nil),                   // 19: queue.Item
	(*queue.ItemState)(nil),              // 20: queue.ItemState
	(*timestamppb.Timestamp)(nil),        // 21: google.protobuf.Timestamp
}
var file_queue_service_proto_depIdxs = []int32{
	18, // 0: queue_svc.ClearHistoryInput.queue:type_name -> queue.Identifier
	18, // 1: queue_svc.GetFinishedItemsInput.queue:type_name -> queue.Identifier
	17, // 2: queue_svc.GetFinishedItemsInput.pagination:type_name -> queue_svc.PaginationParameters
	17, // 3: queue_svc.GetFinishedItemsResult.pagination:type_name -> queue_svc.PaginationParameters
	12, // 4: queue_svc.GetFinishedItemsResult.items:type_name -> queue_svc.IdentifiedQueueItemWithState
	18, // 5: queue_svc.ClaimNextItemInput.queue:type_name -> queue.Identifier
	18, // 6: queue_svc.ClaimNextItemResult.id:type_name -> queue.Identifier
	19, // 7: queue_svc.ClaimNextItemResult.item:type_name -> queue.Item
	18, // 8: queue_svc.SetItemStateInput.item:type_name -> queue.Identifier
	20, // 9: queue_svc.SetItemStateInput.state:type_name -> queue.ItemState
	17, // 10: queue_svc.SetItemStateResult.pagination:type_name -> queue_svc.PaginationParameters
	12, // 11: queue_svc.SetItemStateResult.items:type_name -> queue_svc.IdentifiedQueueItemWithState
	18, // 12: queue_svc.GetQueueItemsInput.queue:type_name -> queue.Identifier
	17, // 13: queue_svc.GetQueueItemsInput.pagination:type_name -> queue_svc.PaginationParameters
	17, // 14: queue_svc.GetQueueItemsResult.pagination:type_name -> queue_svc.PaginationParameters
	12, // 15: queue_svc.GetQueueItemsResult.items:type_name -> queue_svc.IdentifiedQueueItemWithState
	18, // 16: queue_svc.CancelItemInput.item:type_name -> queue.Identifier
	18, // 17: queue_svc.IdentifiedQueueItemWithState.id:type_name -> queue.Identifier
	19, // 18: queue_svc.IdentifiedQueueItemWithState.item:type_name -> queue.Item
	20, // 19: queue_svc.IdentifiedQueueItemWithState.state:type_name -> queue.ItemState
	21, // 20: queue_svc.IdentifiedQueueItemWithState.updated:type_name -> google.protobuf.Timestamp
	18, // 21: queue_svc.EnqueueItemInput.queue:type_name -> queue.Identifier
	19, // 22: queue_svc.EnqueueItemInput.item:type_name -> queue.Item
	18, // 23: queue_svc.EnqueueItemResult.id:type_name -> queue.Identifier
	18, // 24: queue_svc.CreateQueueResult.id:type_name -> queue.Identifier
	18, // 25: queue_svc.PaginationParameters.next:type_name -> queue.Identifier
	15, // 26: queue_svc.QueueService.CreateQueue:input_type -> queue_svc.CreateQueueInput
	13, // 27: queue_svc.QueueService.EnqueueItem:input_type -> queue_svc.EnqueueItemInput
	10, // 28: queue_svc.QueueService.CancelItem:input_type -> queue_svc.CancelItemInput
	8,  // 29: queue_svc.QueueService.GetQueueItems:input_type -> queue_svc.GetQueueItemsInput
	2,  // 30: queue_svc.QueueService.GetFinishedItems:input_type -> queue_svc.GetFinishedItemsInput
	6,  // 31: queue_svc.QueueService.SetItemState:input_type -> queue_svc.SetItemStateInput
	4,  // 32: queue_svc.QueueService.ClaimNextItem:input_type -> queue_svc.ClaimNextItemInput
	0,  // 33: queue_svc.QueueService.ClearHistory:input_type -> queue_svc.ClearHistoryInput
	16, // 34: queue_svc.QueueService.CreateQueue:output_type -> queue_svc.CreateQueueResult
	14, // 35: queue_svc.QueueService.EnqueueItem:output_type -> queue_svc.EnqueueItemResult
	11, // 36: queue_svc.QueueService.CancelItem:output_type -> queue_svc.CancelItemResult
	9,  // 37: queue_svc.QueueService.GetQueueItems:output_type -> queue_svc.GetQueueItemsResult
	3,  // 38: queue_svc.QueueService.GetFinishedItems:output_type -> queue_svc.GetFinishedItemsResult
	7,  // 39: queue_svc.QueueService.SetItemState:output_type -> queue_svc.SetItemStateResult
	5,  // 40: queue_svc.QueueService.ClaimNextItem:output_type -> queue_svc.ClaimNextItemResult
	1,  // 41: queue_svc.QueueService.ClearHistory:output_type -> queue_svc.ClearHistoryResult
	34, // [34:42] is the sub-list for method output_type
	26, // [26:34] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_queue_service_proto_init() }
func file_queue_service_proto_init() {
	if File_queue_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_queue_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearHistoryInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearHistoryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFinishedItemsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFinishedItemsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimNextItemInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimNextItemResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemStateInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetItemStateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueueItemsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueueItemsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelItemInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelItemResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentifiedQueueItemWithState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueueItemInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueueItemResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQueueInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQueueResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queue_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_service_proto_goTypes,
		DependencyIndexes: file_queue_service_proto_depIdxs,
		MessageInfos:      file_queue_service_proto_msgTypes,
	}.Build()
	File_queue_service_proto = out.File
	file_queue_service_proto_rawDesc = nil
	file_queue_service_proto_goTypes = nil
	file_queue_service_proto_depIdxs = nil
}
